services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=lms
    ports:
      - "5444:5432"
    volumes:
      - db:/var/lib/postgresql/data

  web:
    env_file:
      - .env
    build: .
    command: ["uvicorn", "LMS.asgi:application", "--host", "0.0.0.0", "--port", "5009","--reload"]
    volumes:
      - .:/app
    ports:
      - "5009:5009"
    depends_on:
      - db

  redis:
    image: "redis:alpine"
    ports:
      - "6369:6379"

  celery:
    build: .
    env_file:
      - .env
    command: ["celery", "-A", "LMS", "worker", "--loglevel=info"]
    depends_on:
      - redis
      - db
    volumes:
      - .:/app

  cron:
    build: .
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - db
    command: cron -f

volumes:
  db:
    driver: local
