BBBB BBBBBB
XXXXXXXXX XXXXX
XXXXX XXXXXXXXXX
XXXXXX
    XXXXX XXXXXXXXXXXXXXXX
    XXXXXXXXXXXX XXXXXXXXXXXXX
    XXXXXXX
        XXXX X
            XXXXXXXXXXXX XXXXXX XXXXXXXXXXX
            XXXXXXX XX
            
        X

        XXXXXXXXXXXXX X
            XXXXXXXXXXXXXXXXX XXXXXXX
            XXXXXXXX XXXXXX
            XXXXXXXXXXXXXXX XXXXXXX
            XXXXXXXXXXXXXXXX XXXXXXX
            
            
            
        X

        XX XXXXXX XXXX XXXXX XXXXX XXX XXXX XXXX XX
        XXXXXXXXXXXXXXXXXXXXXXXX X
            XXXXXXXXXXXXXXXXX XXXXX
        X

        XXXXXXXXXXXXXX X
            XXXXXX XXXXXX
            XXXXXXX XXXXX
        X

        XXXXX X
            XXXXXX XXXXX
            XXXXXXXXXXXXXXXX XXXXXXXXX
            XXXXXXXXXXX XXXXX
        X

        XXX XX X
            XXXXXXX XXX XXXXX XXXXX
            XXXXXXXX XXXXX
            XXXXXXXXXXX XXXXX
        X

        XX X
            XXXXXXXXXXXXXXXXX XXXXXXXX
        X

        XX X
            XXXXXXXXXXXXXX XXXXX
        X

        XXXXXX
            XXXXXXXX XXXXX
            XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
        X

        XXXXXXXXXXXXXXXXX
            XXXXXXX XXXXXX
            XXXXXX XXXXXX
        X

        XXXXXXXXXXXXXXXXXXXXX
            XXXXXX XXXXX
            XXXXXXX XXXXX
        X

        XXXXXXXXXXXXX
            XXXXXX XXXXX
            XXXXXXX XXXXX
        X
    XXXXXXXX
XXXXXXX
XXXXXX
    BBB BBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBBBBBBBBBBB
    XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXX XXXXX XXXXX XXXXXXXX XXXXXX
        XXXX XXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXX

        XXXXXX
            BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
                XXXX XXXXXXXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXX XXXXX X

                XXXXXX
            BBBB
                XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXX
                    XX XXXXXXXXXXXXXXXXXXX XXXXXX X XXXXXXXX XXXX
                XXXXXXXXXX XXXXXXXXXX XXXX X XXXXXXX XXXX XXXXXXX XX XXXX XXX
            BBBBB

        XXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX XXXXXX
            XXXXXXXXXXXXXXX XXXXX

        XXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX XXXXXX
            XXXXXXXXX X XXXXXX XXXXX
        XXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX XXXXX XXXXXXXXXXXXXX XXXXXX
            XXXX  XXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXX
        XXXXXX
        XXXXXXX
            XXXXXXX
                XXXX
                    XXXXXXXX X XXXXXXXXXXXX
                    XXXX XXXXX
                XXXXX
                XXXX
                    XXXXXXXXXXXXX XXXXXXX
                    XXXXXXXXX
                XXXXX
                XXXX
                    XXXXXXXXXXXXXXXX
                    XXXXXXXXXXX
                XXXXX
                XXXX
                    XXXXXXXXXXXXX
                    XXXXXXXXX
                XXXXX
                XXXX
                    XXXXXXXXXXXXX
                    XXXXXXXXX
                XXXXX
                XXXX

                    XXXXXXXXXXXXX
                    XXXX FFFFFFFFFFFF X FFFFFFFFF FF X  FFFFFFFFF FFXXXXXX
                XXXXX
            XXXXXXXX

        XXXXXXXX
    XXXXXX
    BBBBBB
XXXXXXX
XXXXXXX