# Generated by Django 5.1.2 on 2025-03-18 07:07

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nest_db_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('quiz_topic', models.CharField(max_length=255)),
                ('quiz_type', models.CharField(choices=[('school', 'school'), ('self', 'self'), ('ai', 'ai')], max_length=100)),
                ('weaknesses', models.JSONField(blank=True, null=True)),
                ('number_of_questions', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quiz_start_date_time', models.DateTimeField()),
                ('quiz_end_date_time', models.DateTimeField()),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nest_db_app.batch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nest_db_app.user')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nest_db_app.grade')),
                ('grade_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nest_db_app.gradeclass')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nest_db_app.school')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nest_db_app.subject')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nest_db_app.term')),
            ],
            options={
                'verbose_name': 'MainQuiz',
                'db_table': 'main_quiz',
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('quiz_topic', models.CharField(max_length=255)),
                ('quiz_type', models.CharField(choices=[('school', 'school'), ('self', 'self'), ('ai', 'ai')], max_length=100)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('number_of_questions', models.IntegerField(blank=True, null=True)),
                ('marks_obtained', models.IntegerField(blank=True, null=True)),
                ('is_attempted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quiz_start_date_time', models.DateTimeField()),
                ('quiz_end_date_time', models.DateTimeField()),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nest_db_app.batch')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nest_db_app.grade')),
                ('grade_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nest_db_app.gradeclass')),
                ('main_quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personalized_learning.mainquiz')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nest_db_app.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nest_db_app.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nest_db_app.subject')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nest_db_app.term')),
            ],
            options={
                'verbose_name': 'Quiz',
                'db_table': 'quiz',
            },
        ),
        migrations.CreateModel(
            name='QuizQandA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('options', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, null=True, size=None)),
                ('actual_answers', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, null=True, size=None)),
                ('student_answers', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, null=True, size=None)),
                ('multi_choice', models.BooleanField(default=False)),
                ('is_correct', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nest_db_app.batch')),
                ('quiz', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='personalized_learning.quiz')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nest_db_app.school')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nest_db_app.term')),
            ],
            options={
                'verbose_name': 'QuizQandA',
                'db_table': 'quiz_q_and_a',
            },
        ),
    ]
