XXXXX XXXXXXXXXX
XXXXXX
    XXXXX XXXXXXXXXXXXXXX XX
    XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XX
    XXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX
XXXXXXX

XXXXX XXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXX XXXXXX XXXXX XXXXXXXXXXXX XXXX XXXXXXX XX XXXXXXXX XX XXXXXXXXXXXXXXXXX XXXXXXXXX
XXXX
        XXXXXXX
                XXXXXXXXXX XXXXXX
                XXXXXXX XXXX XXXXX
                XXXXXXXXXXXXXXXXX XXXXXXXX
                XXXXXXXXXXXXXX XXXX
                XXXXXXXXXXX X XXX XXXX XXXXXXX XX XX XXXXX
                XXXXXXXXX XXXXXXX
            X
X
    XXXXX
        XXXXXXX
                XXXXXXX
                        XXXXXXXXXXXXXXXXX XXXXXXXX
                        XXXXXX XXXXXX
                        XXXXXXXX XXXXX
                        XXXXXXXXXXX XXXXXXX
                        XXXXXXXXXXXXXXXXXXXXXXX XXXX
                        XXXXXXXXXXXXXXXXXXXXXXXX XXXX
                    X
        X
            XXX XXXXXXXXXXXXXXXXX XXXXX XXXXXXX XXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX
            XX XXXXXXXXXXXXXXXXX XXXXX XXXXXXX XXXXXXXXX XXXXXX XXX XXXXXX XXXXX XXXXXXXXXX
        XXXXXXXXX
        XXXX XXXXXXXXXXXXXXX XXXXX XXXXXXXXXXX XXXXX XXXXXX XXXXXX
            XXXXXXXXXX XXXXXXXXXXXXX
            XX XXXXXXXXXXXXXXXXX XXXXX XXXXXXX XXXX XXX
                XXX XXXXXXXXX XXXXXX XXXXXX XXXXXXX XXXXXXXX XXXXXXXX XXX XX XXXXXXXXXX XXXXX XXXX XXX
                XXXXXXX XXXXXXX XXXXXX XXXXXXXX XXXXXXXX
            XXXX
            XX XXXXXXXXXXXXXXXXX XXXXX XXXXXXX XXXX XXX

                XXXXXXXXXXXXXXXXXX XXXX
                XXXXXXXX XXXXXXXXXX  XXXX

                XXXXXXX XX XXXXXXXXXXXXX
            XXXX
            XXX XXXXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXX XX XXXXXXX XXX
                BBB BBBBBBB BB BBBBBBBB
                    XXX XXXXXXXXXXXXXXXXXXXXX XXXXXX
                        X XXXXXXXXXXXXXXXXX XXXXXXXXXX XXX X
                    XXXXX
                BBBBBB
            XXXXX
            XX XXXXXXXXXXXXXXXXX XXXXX XXXXXXX XXXX XXX
                XXXXXX XXXX XXX XXXXXXXXX XXXXX XX XXXXXX XXX XXXXXX XXXXXX XXX XXXXXXX XXXXX XXX XXX XXXXXXXXXX
                XXXXXX XXXXXX
            XXXX

            XXXX XXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXX XXXXXXXX
                XX
                        XXXXXXX
                        XXXXXXX
                                XXXXXXXX XXXXXXXXXXXXX
                                XXXXXXXX XXXX XXXXX
                                XXXXXXXXXXXXXXXXX XXXXXXXX
                                XXXXXX XXXXX
                                XXXXXXXXXX XXXXX
                                XXXXXXXXXXX XXXXXXX
                                XXXXXXXXXXXXXXXX XXXXX
                                XXXXXXXXXXXXXX XXXX
                                XXXXXXX XXXXXXXX
                            X
                XXXXXXX XXXXXX
                X
            XXXXXX
            XXXX
                    XXXXXX
                    XXXXXXXXXXX
                    XXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXXXXXXXXXXX XXXXXX XXXXXXXXXX XXXXXX XXXXXXX XXXX XXXXX
            XX
        XXXXXX
        XXXXXXX
                XXXXXXX
                        XXXXXXXXXXXXXXXXX XXXXXXXX
                        XXXXXXXX XXXXX
                        XXXXXXXXXXX XXXXXXX
                        XXXXXXXXXX XXXXX
                        XXXXXXXXXXXXXXXXXXXXXXXXXX XXXX
                        XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXX
                    X
        X
            XX XXXXXXXXXXXXXX XXXXXXXXX  XXXXXXXX XXX XXXXXX XXXXXXXXXXXXX
        XXXXXXXXX
    XXXXXX
XXXXXX
XXXXXXX
XXXXXXX